### ISSUE TITLE
Segmentation included

### ISSUE THREAD

**Issue by MB-Mtl** [mahendrakhened/Automated-Cardiac-Segmentation-and-Disease-Diagnosis#1]
It's not clear if this code performs segmentation or is it assuming a pre-trained model?

**Comment by mahendrakhened** [comment]
I had uploaded only the code to do feature extract features and disease classification. Will upload code to segmentation shortly

**Comment by jiejiangd** [comment]
May I ask how to set up patch_size?

**Comment by mahendrakhened** [comment]
The patch size needs to be changed in the file: Automated-Cardiac-Segmentation-and-Disease-Diagnosis/estimators/config.py .

Line Number 42.
		# Set patch extraction parameters
		size0 = (64, 64)
		size1 = (128, 128)
		size2 = (256, 256)
		patch_size = size1

**Comment by jiejiangd** [comment]
Thank you very much.
 
 
------------------ Original ------------------

**Comment by jiejiangd** [comment]
Sorry to interrupt you again. I made the mistake three times in the training process, such as the screenshot of the attachment. I don't know what the reason is. Do I need to add an exception handling mechanism in the corresponding position to prevent the overflow of subscripts?
 
 
------------------ Original ------------------

**Comment by mahendrakhened** [comment]
I am not able to see any attachment. Could you describe the error. Please do consider adding exception handling mechanism if you see an overflow of some subscripts.

**Comment by jiejiangd** [comment]
------------------ Original ------------------

**Comment by jiejiangd** [comment]
I'm sorry to bother you again, but I want to ask you where the image visualization part of the code is.And there's a question, the size of the picture output from the test seems to be different, but I'm still reading the code and maybe I haven't read it in some places yet.
 
------------------ Original ------------------

**Comment by jiejiangd** [comment]
The size of the region of interest in the first case I saw in the h5py file is 256 x 216.
 
 thank you!

------------------ Original ------------------
From:  "黄英杰"<201821562004@smail.xtu.edu.cn>;
Date:  Thu, Jan 17, 2019 09:27 PM
To:  "mahendrakhened/Automated-Cardiac-Segmentation-and-Disease-Diagnosis"<reply@reply.github.com>; 

Subject:  Re: [mahendrakhened/Automated-Cardiac-Segmentation-and-Disease-Diagnosis] Segmentation included (#1)

 
I'm sorry to bother you again, but I want to ask you where the image visualization part of the code is.And there's a question, the size of the picture output from the test seems to be different, but I'm still reading the code and maybe I haven't read it in some places yet.
 
------------------ Original ------------------

**Comment by jiejiangd** [comment]
ValueError: I/O operation on closed file


When I run the plot_roi() function in the acdc_data_preparation.py file, there are always the above errors. I don't know how to solve them. When I comment out anim. save ('Cine_MRI_SAX_% d.mp4'% slice_cnt, fps=50, extra_args=['-vcodec','libx264'), there are no errors. But I want to save the image in MP4 format, and ask for information. Thank you.

 
------------------ Original ------------------

**Comment by mahendrakhened** [comment]
Thank you. Are you able to fix the above errors and use the repository?
