### ISSUE TITLE
Encountered an error

### ISSUE THREAD

**Issue by alimsvn** [mahendrakhened/Automated-Cardiac-Segmentation-and-Disease-Diagnosis#2]
Dear mahendra;
When I run the acdc_data_preparation.py this error comes up:
No such file or directory: 'My Drive/ACDC_DataSet/training/training/Info.cfg'.
Should I combine all info.cfg files from each patient folder and put it into training subfolder?
thanks.

**Comment by mahendrakhened** [comment]
The code should work as it is. No need to combine all info.cfg. Kindly check the data path in your system.
